### ISSUE TITLE
Death from Prostate Cancer

### ISSUE THREAD

**Issue by anneserious** [jebibault/ProstateCancerSurvival#1]
Hello,
I came across this repo due to your interesting recent paper in Cancers. I have also had a look at the PLCO dataset and tried to reproduce the number of patients who died of prostate cancer (your primary endpoint).
By using the feature "d_dthp", I was able to identify 543 PCa-deaths. In your paper, you mention 682 patients who died of prostate cancer. May I ask how you reached this number?

Thank you and kind regards
Anne

**Comment by jebibault** [comment]
Hi,
You need to use "f_dthp", which is based on the information from the death certificate and death review. I think this is more relevant than "d_dthp", which is based only on the information from the death certificate.

Best,

**Comment by anneserious** [comment]
Hi,
thanks for your helpful reply! However, using "f_dthp" I can only find 546 patients who died of prostate cancer. Allowing "f_dthp" OR "d_dthp", I can identify 561 patients. Do you use any other criteria, or maybe we are working with different versions of the data?
Thanks and kind regards
Anne

**Comment by jebibault** [comment]
Hi,
I don't use any other criteria. I'm using the dataset from July 2019.
Best regards,
